---
title: "RS04.Env"
author: "Jay"
date: "2024-03-08"
output: html_document
---

simple linear regression/logistic regression to test the association between restoration score and environmental factors 
1. in full cohort
2. in cs stratum

set output path
```{r}
outpath <- "../results/RS04.Env"
dir.create(outpath)
```

#prepare data and load packages
```{r}
load("../data/phy_3timepoints_restoration_score.rdata")
library(phyloseq)
library(copiome)
library(magrittr)
library(broom)
library(ggplot2)
source("../jay_small_functions/perform_linear_regression.R")
samp <- sample_df(phy_3timepoints) %>% subset(Visit == "1 year")
samp$restoration_score <- scale(samp$restoration_score)

samp_cs <- sample_df(phy_3timepoints) %>% subset(Visit == "1 year" & delivery == "c_section")
samp_cs$restoration_score <- scale(samp_cs$restoration_score)
```


#perform linear/logistic regression on environmental factors VS CS score
## in full cohort
```{r}
col1 <- which(colnames(samp) == "delivery")
col2 <- which(colnames(samp) == "restoration_score")
samp_lm <- samp[,c(col1:col2)] %>% dplyr::select(-sibling_age,-CS_Preds_PLS_1y)

invars <- samp_lm %>% dplyr::select(-restoration_score) %>% colnames(.)
outvars <- "restoration_score"


# Initialize an empty data frame to store results
results <- data.frame()

# Loop through invars and outvars to perform linear regression
for(invar in invars) {
  for(outvar in outvars) {
    # Construct the linear regression model formula
    formula <- as.formula(paste(outvar, "~", invar, "+ delivery"))
    
    # Perform linear regression analysis
    model <- lm(formula, data = samp_lm)
    
    # Tidy the model results and remove intercept and delivery term
    tidy_model <- tidy(model, conf.int = TRUE) %>% slice(-1, -3)
    
    # Add number of tests for continuous variables and proportion of the second level for categorical variables
    if(is.numeric(samp_lm[[invar]])) {
      num_tests <- sum(!is.na(samp_lm[[invar]]))  # Number of non-NA observations for continuous variables
      tidy_model <- tidy_model %>% mutate(num_tests = num_tests, ref_group_prop = NA, level_name = NA)
    } else {
      levels <- levels(samp_lm[[invar]])
      if(length(levels) >= 2) {
        # Use the mean trick to calculate the proportion of the second level
        ref_group_prop <- mean(samp_lm[[invar]] == levels[2], na.rm = TRUE)  # Ignore NA values
        tidy_model <- tidy_model %>% mutate(num_tests = NA, ref_group_prop = ref_group_prop, level_name = levels[2])
      } else {
        tidy_model <- tidy_model %>% mutate(num_tests = NA, ref_group_prop = NA, level_name = NA)
      }
    }
    
    # Add original variable name for later use
    tidy_model <- tidy_model %>% mutate(original_var = invar)
    
    # Append the results to the results data frame
    results <- rbind(results, tidy_model)
  }
}

# Remove rows with NA in num_tests or ref_group_prop
results <- results %>% filter(!is.na(num_tests) | !is.na(ref_group_prop))

# Arrange results by p-value
results <- results %>% dplyr::arrange(p.value)

# Add significance and color coding
results <- results %>%
  mutate(significant = p.value < 0.05,  # Define significance
         sign_color = case_when(
           significant & estimate < 0 ~ "Significant Negative",  # Significant and negative
           significant & estimate >= 0 ~ "Significant Positive",  # Significant and positive
           TRUE ~ "Not Significant"  # Not significant
         ))

# Update y-axis label with original variable name and proportion of reference group
results <- results %>%
  mutate(y_label = case_when(
    !is.na(num_tests) ~ paste(original_var, " (N = ", num_tests, ")", sep = ""),
    !is.na(ref_group_prop) ~ paste(original_var, " (", level_name, ": ", round(ref_group_prop * 100, 2), "%)", sep = ""),
    TRUE ~ original_var
  ))


results$p.value_adj <- p.adjust(results$p.value, method = "fdr")

```


```{r}
# Reference data frame with y_labels, readable labels, and groups
group_info <- data.frame(
  y_label = c(
    "oldchild_yn (yes: 55.66%)",               
    "delivery (c_section: 21.37%)",            
    "sibling_age_imputed (N = 364)",            
    "atb_birth_child (yes: 2.56%)",            
    "birth_area (rural: 46.52%)",              
    "atb_birth_mother (yes: 31.57%)",         
    "daycare_startage (N = 626)",               
    "ab_preg_yn (yes: 35.78%)",                
    "any_breastmilk_6mon (yes: 68.32%)",       
    "ab_child_3m_ever (yes: 6.12%)",               
    "mother_astdoc (yes: 26.32%)",             
    "father_dermdoctor (yes: 15.07%)",        
    "mother_bmi (N = 623)",                     
    "ab_child_number_3m (N = 621)",             
    "cat_yn (yes: 22.76%)",                    
    "ab_preg_third_yn (yes: 17.41%)",          
    "ab_child_number_1y (N = 621)",             
    "ab_preg_second_yn (yes: 16.13%)",        
    "dog_yn (yes: 21.63%)",                    
    "father_astdoc (yes: 21.84%)",             
    "ab_child_1yr_ever (yes: 45.89%)",              
    "fatherage (N = 612)",                      
    "ab_preg_first_yn (yes: 12.14%)",          
    "exclusive_breastmilk_6mon (yes: 5.75%)", 
    "exclusive_breastmilk_4mon (yes: 56.87%)", 
    "exclusive_breastmilk_1mon (yes: 79.87%)", 
    "motherage (N = 627)",                      
    "mother_rhindoctor (yes: 32.22%)",         
    "father_rhindoctor (yes: 29.49%)",         
    "furanimal_child_yn (yes: 83.17%)",       
    "mother_dermdoctor (yes: 27%)",            
    "age_days (N = 627)",                       
    "any_breastmilk_1wk (yes: 98.08%)",        
    "any_breastmilk_1mon (yes: 93.92%)",       
    "hospitalization_yn (yes: 11.8%)",         
    "exclusive_breastfeed_ever (yes: 95.85%)",
    "exclusive_breastmilk_1wk (yes: 90.58%)",  
    "any_breastmilk_4mon (yes: 81.76%)",       
    "any_breastmilk_ever (yes: 99.04%)",       
    "any_breastmilk_1yr (yes: 15.52%)"  
  ),
  readable_label = c(
    "Having older siblings (yes: 55.66%)",               
    "Delivery mode (c_section: 21.37%)",            
    "Age of the youngest sibling (N = 364)",            
    "Antibiotics to children at birth (yes: 2.56%)",            
    "Birth area (rural: 46.52%)",              
    "Antibiotics to mother at birth (yes: 31.57%)",         
    "Age when starting daycare (N = 626)",               
    "Antibiotics during pregnancy (yes: 35.78%)",                
    "Any breastfeeding for 6 months (yes: 68.32%)",       
    "Antibiotics to children in first 3 months (yes: 6.12%)",               
    "Mother asthma history (yes: 26.32%)",             
    "Father dermatitis history (yes: 15.07%)",        
    "Maternal BMI (N = 623)",                     
    "Number of antibiotics to children in first 3 months (N = 621)",             
    "Cat in the home (yes: 22.76%)",                    
    "Antibiotics during third trimester (yes: 17.41%)",          
    "Number of antibiotics to children in first year (N = 621)",             
    "Antibiotics during second trimester (yes: 16.13%)",        
    "Dog in the home (yes: 21.63%)",                    
    "Father asthma history (yes: 21.84%)",             
    "Antibiotics to children in first year (yes: 45.89%)",              
    "Paternal age (N =612)",                      
    "Antibiotics during first trimester (yes: 12.14%)",          
    "Exclusive breastfeeding for 6 months (yes: 5.75%)", 
    "Exclusive breastfeeding for 4 months (yes: 56.87%)", 
    "Exclusive breastfeeding for 1 month (yes: 79.87%)", 
    "Maternal age (N = 627)",                      
    "Mother rhinitis history (yes: 32.22%)",         
    "Father rhinitis history (yes: 29.49%)",         
    "Furry animals in the home (yes: 83.17%)",       
    "Mother dermatitis history (yes: 27%)",            
    "Gestational age in days (N = 627)",                       
    "Any breastfeeding for 1 week (yes: 98.08%)",        
    "Any breastfeeding for 1 month (yes: 93.92%)",       
    "Hospitalization after birth (yes: 11.8%)",         
    "Exclusive breastfeeding ever (yes: 95.85%)",
    "Exclusive breastfeeding for 1 week (yes: 90.58%)",  
    "Any breastfeeding for 4 months (yes: 81.76%)",       
    "Any breastfeeding ever (yes: 99.04%)",       
    "Any breastfeeding for 1 year (yes: 15.52%)"  
  )
)

table(is.na(group_info))

```


```{r}
# Define the desired order of readable labels grouped and ordered alphabetically within groups
desired_order <- c(
  # Paternal Factors
  "Father asthma history (yes: 21.84%)",
  "Father dermatitis history (yes: 15.07%)",
  "Father rhinitis history (yes: 29.49%)",
  "Paternal age (N =612)",
  
  # Maternal Factors
  "Maternal BMI (N = 623)",
  "Maternal age (N = 627)",
  "Mother asthma history (yes: 26.32%)",
  "Mother dermatitis history (yes: 27%)",
  "Mother rhinitis history (yes: 32.22%)",
  
  # Birth and Delivery Factors
  "Antibiotics during pregnancy (yes: 35.78%)",
  "Antibiotics during first trimester (yes: 12.14%)",
  "Antibiotics during second trimester (yes: 16.13%)",
  "Antibiotics during third trimester (yes: 17.41%)",
  "Delivery mode (c_section: 21.37%)",
  "Gestational age in days (N = 627)",
  
  # Antibiotic Use
  "Antibiotics to mother at birth (yes: 31.57%)",
  "Antibiotics to children at birth (yes: 2.56%)",
  "Antibiotics to children in first 3 months (yes: 6.12%)",
  "Antibiotics to children in first year (yes: 45.89%)",
  "Number of antibiotics to children in first 3 months (N = 621)",
  "Number of antibiotics to children in first year (N = 621)",
  
  # Breastfeeding
  "Any breastfeeding ever (yes: 99.04%)",
  "Any breastfeeding for 1 week (yes: 98.08%)",
  "Any breastfeeding for 1 month (yes: 93.92%)",
  "Any breastfeeding for 4 months (yes: 81.76%)",
  "Any breastfeeding for 6 months (yes: 68.32%)",
  "Any breastfeeding for 1 year (yes: 15.52%)",
  "Exclusive breastfeeding ever (yes: 95.85%)",
  "Exclusive breastfeeding for 1 week (yes: 90.58%)",
  "Exclusive breastfeeding for 1 month (yes: 79.87%)",
  "Exclusive breastfeeding for 4 months (yes: 56.87%)",
  "Exclusive breastfeeding for 6 months (yes: 5.75%)",
  
  # Environmental Exposures
  "Birth area (rural: 46.52%)",
  "Cat in the home (yes: 22.76%)",
  "Dog in the home (yes: 21.63%)",
  "Furry animals in the home (yes: 83.17%)",
  
  # Family Characteristics
  "Having older siblings (yes: 55.66%)",
  "Age of the youngest sibling (N = 364)",
  
  # Childcare Factors
  "Age when starting daycare (N = 626)",
  
  # Child Health Outcomes
  "Hospitalization after birth (yes: 11.8%)"
)
# Merge results with group_info to add readable labels and groups
results <- merge(results, group_info, by = "y_label")
results[is.na(results$readable_label),]


env_lm_table_full <- results %>% select(readable_label,estimate, conf.low, conf.high, p.value, p.value_adj) %>% 
  mutate(estimate = round(estimate,2),
         conf.low = round(conf.low, 2),
         conf.high = round(conf.high,2),
         p.value = round(p.value,2),
         p.value_adj = round(p.value_adj,2),
         readable_label = factor(readable_label, levels = desired_order)
         )
env_lm_table_full

# Save the results to a CSV file
tablename1 <- paste0(outpath, "/Env_vs_restoration_score_lm.xlsx")
writexl::write_xlsx(env_lm_table_full, tablename1)
```

```{r}
# Order the y_label based on the reference order in group_info
results$readable_label <- factor(results$readable_label, levels = desired_order)

# Your ggplot call
p <- ggplot(results, aes(x = factor(readable_label, levels = desired_order), y = estimate, fill = sign_color)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.5)) +
  geom_errorbar(data = filter(results, significant),  
                aes(ymin = conf.low, ymax = conf.high), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("Significant Negative" = "#0072B2", "Significant Positive" = "#D55E00", "Not Significant" = "grey"), name = "Significance Level") +
  labs(x = NULL, y = "Estimate") +
  ggtitle("In full cohort") +
  theme_minimal() +
  coord_flip();p

# Save the plot
plotname <- paste0(outpath, "/Restoration_score_VS_Env.pdf")
ggsave(plotname, p, width = 8, height = 8)

save(p, file = paste0(outpath, "/Restoration_score_VS_Env.RData"))

```






## in cs stratum
```{r}
col1 <- which(colnames(samp_cs) == "delivery")
col2 <- which(colnames(samp_cs) == "restoration_score")
samp_lm_cs <- samp_cs[,c(col1:col2)] %>% dplyr::select(-delivery,-atb_birth_mother,-atb_birth_child,-sibling_age,-CS_Preds_PLS_1y) 

invars <- samp_lm_cs %>% dplyr::select(-restoration_score) %>% colnames(.)
outvars <- "restoration_score"

# Initialize an empty data frame to store results
results <- data.frame()

# Loop through invars and outvars to perform linear regression
for(invar in invars) {
  for(outvar in outvars) {
    # Construct the linear regression model formula
    formula <- as.formula(paste(outvar, "~", invar))
    
    # Perform linear regression analysis
    model <- lm(formula, data = samp_lm_cs)
    
    # Tidy the model results and remove intercept
    tidy_model <- tidy(model, conf.int = TRUE) %>% slice(-1)
    
    # Add number of tests for continuous variables and proportion of the second level for categorical variables
    if(is.numeric(samp_lm_cs[[invar]])) {
      num_tests <- sum(!is.na(samp_lm_cs[[invar]]))  # Number of non-NA observations for continuous variables
      tidy_model <- tidy_model %>% mutate(num_tests = num_tests, ref_group_prop = NA, level_name = NA)
    } else {
      levels <- levels(samp_lm_cs[[invar]])
      if(length(levels) >= 2) {
        # Use the mean trick to calculate the proportion of the second level
        ref_group_prop <- mean(samp_lm_cs[[invar]] == levels[2], na.rm = TRUE)  # Ignore NA values
        tidy_model <- tidy_model %>% mutate(num_tests = NA, ref_group_prop = ref_group_prop, level_name = levels[2])
      } else {
        tidy_model <- tidy_model %>% mutate(num_tests = NA, ref_group_prop = NA, level_name = NA)
      }
    }
    
    # Add original variable name for later use
    tidy_model <- tidy_model %>% mutate(original_var = invar)
    
    # Append the results to the results data frame
    results <- rbind(results, tidy_model)
  }
}

# Remove rows with NA in num_tests or ref_group_prop
results_cs <- results %>% filter(!is.na(num_tests) | !is.na(ref_group_prop))

# Arrange results by p-value
results_cs <- results_cs %>% dplyr::arrange(p.value)

# Add significance and color coding
results_cs <- results_cs %>%
  mutate(significant = p.value < 0.05,  # Define significance
         sign_color = case_when(
           significant & estimate < 0 ~ "Significant Negative",  # Significant and negative
           significant & estimate >= 0 ~ "Significant Positive",  # Significant and positive
           TRUE ~ "Not Significant"  # Not significant
         ))

# Update y-axis label with original variable name and proportion of reference group
results_cs <- results_cs %>%
  mutate(y_label = case_when(
    !is.na(num_tests) ~ paste(original_var, " (N = ", num_tests, ")", sep = ""),
    !is.na(ref_group_prop) ~ paste(original_var, " (", level_name, ": ", round(ref_group_prop * 100, 2), "%)", sep = ""),
    TRUE ~ original_var
  ))

results_cs$p.value_adj <- p.adjust(results_cs$p.value, method = "fdr")
results_cs %>% filter(p.value_adj<0.05)
```


#

```{r}
# Creating the group_info data frame
group_info <- data.frame(
  y_label = c(
    "any_breastmilk_6mon (yes: 63.91%)",
    "cat_yn (yes: 26.32%)",
    "oldchild_yn (yes: 50.75%)",
    "birth_area (rural: 49.61%)",
    "father_dermdoctor (yes: 9.68%)",
    "sibling_age_imputed (N = 70)",
    "exclusive_breastmilk_4mon (yes: 50.75%)",
    "any_breastmilk_4mon (yes: 77.44%)",
    "furanimal_child_yn (yes: 82.71%)",
    "ab_child_3m_ever (yes: 8.27%)",
    "ab_child_number_3m (N = 133)",
    "any_breastmilk_1yr (yes: 16.54%)",
    "mother_dermdoctor (yes: 26.12%)",
    "daycare_startage (N = 133)",
    "ab_preg_yn (yes: 38.06%)",
    "any_breastmilk_1mon (yes: 92.48%)",
    "father_rhindoctor (yes: 27.42%)",
    "hospitalization_yn (yes: 19.4%)",
    "exclusive_breastmilk_6mon (yes: 6.72%)",
    "exclusive_breastmilk_1mon (yes: 71.64%)",
    "dog_yn (yes: 20.3%)",
    "age_days (N = 134)",
    "any_breastmilk_ever (yes: 98.5%)",
    "mother_bmi (N = 132)",
    "fatherage (N = 128)",
    "exclusive_breastmilk_1wk (yes: 82.84%)",
    "ab_child_number_1y (N = 133)",
    "ab_child_1yr_ever (yes: 48.87%)",
    "father_astdoc (yes: 21.43%)",
    "ab_preg_second_yn (yes: 19.4%)",
    "mother_rhindoctor (yes: 34.33%)",
    "any_breastmilk_1wk (yes: 96.24%)",
    "ab_preg_first_yn (yes: 14.93%)",
    "motherage (N = 134)",
    "exclusive_breastfeed_ever (yes: 92.54%)",
    "mother_astdoc (yes: 30.6%)",
    "ab_preg_third_yn (yes: 14.18%)"
  ),
  readable_label = c(
    "Any breastfeeding for 6 months (yes: 63.91%)",
    "Cat in the home (yes: 26.32%)",
    "Having older siblings (yes: 50.75%)",
    "Birth area (rural: 49.61%)",
    "Father dermatitis history (yes: 9.68%)",
    "Age of the youngest sibling (N =70)",
    "Exclusive breastfeeding for 4 months (yes: 50.75%)",
    "Any breastfeeding for 4 months (yes: 77.44%)",
    "Furry animals in the home (yes: 82.71%)",
    "Antibiotics to children in first 3 months (yes: 8.27%)",
    "Number of antibiotics to children in first 3 months (N =133)",
    "Any breastfeeding for 1 year (yes: 16.54%)",
    "Mother dermatitis history (yes: 26.12%)",
    "Age when starting daycare (N =133)",
    "Antibiotics during pregnancy (yes: 38.06%)",
    "Any breastfeeding for 1 month (yes: 92.48%)",
    "Father rhinitis history (yes: 27.42%)",
    "Hospitalization after birth (yes: 19.4%)",
    "Exclusive breastfeeding for 6 months (yes: 6.72%)",
    "Exclusive breastfeeding for 1 month (yes: 71.64%)",
    "Dog in the home (yes: 20.3%)",
    "Gestational age in days (N =134)",
    "Any breastfeeding ever (yes: 98.5%)",
    "Maternal BMI (N =132)",
    "Paternal age (N =128)",
    "Exclusive breastfeeding for 1 week (yes: 82.84%)",
    "Number of antibiotics to children in first year (N =133)",
    "Antibiotics to child in first year (yes: 48.87%)",
    "Father asthma history (yes: 21.43%)",
    "Antibiotics during second trimester (yes: 19.4%)",
    "Mother rhinitis history (yes: 34.33%)",
    "Any breastfeeding for 1 week (yes: 96.24%)",
    "Antibiotics during first trimester (yes: 14.93%)",
    "Maternal age (N =134)",
    "Exclusive breastfeeding ever (yes: 92.54%)",
    "Mother asthma history (yes: 30.6%)",
    "Antibiotics during third trimester (yes: 14.18%)"
  )
)



```


```{r}
# # Define the desired order of readable labels grouped and ordered alphabetically within groups
# desired_order <- c(
#   # Paternal Factors
#   "Father asthma history (yes: 21.43%)",
#   "Father dermatitis history (yes: 9.68%)",
#   "Father rhinitis history (yes: 27.42%)",
#   "Paternal age (N =128)",
#   
#   # Maternal Factors
#   "Maternal BMI (N =132)",
#   "Maternal age (N =134)",
#   "Mother asthma history (yes: 30.6%)",
#   "Mother dermatitis history (yes: 26.12%)",
#   "Mother rhinitis history (yes: 34.33%)",
#   
#   # Birth and Delivery Factors
#   "Antibiotics during first trimester (yes: 14.93%)",
#   "Antibiotics during pregnancy (yes: 38.06%)",
#   "Antibiotics during second trimester (yes: 19.4%)",
#   "Antibiotics during third trimester (yes: 14.18%)",
#   "Gestational age in days (N =134)",
#   
#   # Antibiotic Use
#   "Antibiotics to children at birth (yes: 2.56%)", # If relevant, otherwise remove this line
#   "Antibiotics to children in first 3 months (N =133)",
#   "Antibiotics to children in first year (N =133)",
#   "Number of antibiotics to children in first 3 months (N =133)",
#   "Number of antibiotics to children in first year (N =133)",
#   
#   # Breastfeeding
#   "Any breastfeeding ever (yes: 98.5%)",
#   "Any breastfeeding for 1 month (yes: 92.48%)",
#   "Any breastfeeding for 1 week (yes: 96.24%)",
#   "Any breastfeeding for 4 months (yes: 77.44%)",
#   "Any breastfeeding for 1 year (yes: 16.54%)",
#   "Any breastfeeding for 6 months (yes: 63.91%)",
#   "Exclusive breastfeeding ever (yes: 92.54%)",
#   "Exclusive breastfeeding for 1 month (yes: 71.64%)",
#   "Exclusive breastfeeding for 1 week (yes: 82.84%)",
#   "Exclusive breastfeeding for 4 months (yes: 50.75%)",
#   "Exclusive breastfeeding for 6 months (yes: 6.72%)",
#   
#   # Environmental Exposures
#   "Birth area (rural: 49.61%)",
#   "Cat in the home (yes: 26.32%)",
#   "Dog in the home (yes: 20.3%)",
#   "Furry animals in the home (yes: 82.71%)",
#   
#   # Family Characteristics
#   "Having older siblings (yes: 50.75%)",
#   "Age of the youngest sibling (N =70)",
#   
#   # Childcare Factors
#   "Age when starting daycare (N =133)",
#   
#   # Child Health Outcomes
#   "Hospitalization after birth (yes: 19.4%)"
# )

results_cs <- merge(results_cs, group_info, by = "y_label")
results[is.na(results_cs$readable_label),]

env_lm_table_cs <- results_cs %>% select(readable_label,estimate, conf.low, conf.high, p.value,p.value_adj) %>% 
  mutate(estimate = round(estimate,2),
         conf.low = round(conf.low, 2),
         conf.high = round(conf.high,2),
         p.value = round(p.value,2),
         p.value_adj = round(p.value_adj,2))
env_lm_table_cs

# Save the results to a CSV file
tablename1 <- paste0(outpath, "/Env_vs_restoration_score_lm_cs.xlsx")
writexl::write_xlsx(env_lm_table_cs, tablename1)
```



```{r}

# Plot
p <- ggplot(results_cs, aes(x = readable_label, y = estimate, fill = sign_color)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.5), show.legend = TRUE) +
  geom_errorbar(data = filter(results_cs, significant),  # Show error bars only for significant results
                aes(ymin = conf.low, ymax = conf.high), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("Significant Negative" = "#0072B2", "Significant Positive" = "#D55E00", "Not Significant" = "grey"),name = "Significance level") +
  labs(x = NULL, y = "Estimate") +
  ggtitle("In CS stratum") +
  theme_minimal() +
  coord_flip()

# Save the plot
plotname <- paste0(outpath, "/Restoration_score_VS_Env_cs.pdf")
ggsave(plotname, p, width = 8, height = 8)

save(p, file = paste0(outpath, "/Restoration_score_VS_Env_cs.RData"))
# Save the results to a CSV file
tablename1 <- paste0(outpath, "/Env_vs_restoration_score_lm_cs.csv")
write.csv(results_cs, tablename1)

```

#plot 
```{r}
env_lm <- readxl::read_excel("../results/RS04.Env/ENVVSrestoration_score_lm_full_cs.xlsx",col_types = c("text", "text","numeric", "numeric", "numeric", "numeric","numeric", "text","numeric"), na = "NA") %>% 
  as.data.frame()
env_lm$label <- factor(env_lm$label, levels = c("In the full cohort", "In the CS stratum"))

env_lm$`Environmental factors` <- factor(env_lm$`Environmental factors`, levels = unique(env_lm$`Environmental factors`))

env_lm$sign_color = ifelse(env_lm$`P value`<0.05 & env_lm$Estimate<0, "Significant Negative",
                           ifelse(env_lm$`P value`<0.05 & env_lm$Estimate>0, "Significant Positive", "Not Significant"))

library(ggplot2)
library(magrittr)
p <- ggplot(env_lm, aes(x = reorder(`Environmental factors`, -order), y = Estimate, fill = sign_color)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.5), show.legend = TRUE) +
  facet_wrap(~label)+
  coord_flip() +
  geom_errorbar(data = env_lm[!env_lm$sign_color == "Not Significant",],  # Show error bars only for significant results
                aes(ymin = LowCI, ymax = HighCI), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("Significant Negative" = "#0072B2", "Significant Positive" = "#D55E00", "Not Significant" = "grey"),name = "Significance level") +
  labs(x = NULL, y = "Estimate") +
  theme_minimal()+
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 20),
        legend.position = "bottom");p

plotname = paste0(outpath, "/env_VS_restoration_score.pdf")
ggsave(plotname, p, width = 10, height = 7)
```